version: 1
build:
  main: cmd/fury
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 1000000000ufury
  mnemonic: clutch script morning bacon knock unique impact update aisle morning okay
    outer witness liquid ordinary direct mention dove arrow witness speed satisfy
    work any
- name: bob
  coins:
  - 1000000000ufury
  mnemonic: salmon vivid library slow organ flag card check moment venture hip album
    vehicle write curtain often inquiry bid oven charge catch erosion voice unfold
faucet:
  name: null
  coins: []
  host: 0.0.0.0:4500
genesis:
  app_state:
    staking:
      params:
        bond_denom: ufury
  chain_id: pandora-4
validators:
- name: alice
  bonded: 100000000ufury
  app:
    minimum-gas-prices: 0.025ufury
