version: "3.7"
services:
   nginx:
     image: nginx
     container_name: fury_nginx
     restart: unless-stopped
     ports:
       - "80:8081"
     volumes:
       - .infra/nginx/devel.conf:/etc/nginx/conf.d/devel.conf
     links:
       - fury-blockchain
       - fury-swagger

   fury-swagger:
     container_name: fury_swagger
     image: swaggerapi/swagger-ui
     restart: unless-stopped
     environment:
       - BASE_URL=/swagger
       - SWAGGER_JSON=/api-docs/swagger.yaml
     ports: 
      - "8090:8080" 
     volumes:
       - "./docs/static/openapi.yml:/api-docs/swagger.yaml"

  fury-blockchain:
    container_name: fury_blockchain
    platform: linux/amd64
    build:
      context: .
      dockerfile: .infra/dockerfiles/Dockerfile
      target: build-devel
    tty: true
    image: fury-chain:devel
    restart: unless-stopped
    volumes:
      - "./:/app"
    ports:
      - "1317:1317"  API
      - "26658:26657"  
